project:
  type: website
  output-dir: docs

website:
  title: "사회과 예비교사를 위한 AIㆍ디지털 역량 강화 워크숍"
  navbar:
    logo: aiedap_logo.png
    # background: "#cbd5e8"
    left:
      - href: index.qmd
        text: 프로그램 개요
      - href: material.qmd
        text: 강의 자료
      - href: dashboard.qmd
        text: 교수-학습 대시보드
      - href: reference.qmd
        text: 참고문헌
    right: 
      - icon: house-door
        href: https://sangillee.snu.ac.kr/
      - icon: envelope-arrow-up
        href: mailto:si_lee@snu.ac.kr
      - icon: github
        href: https://github.com/sangillee66
  # comments: 
  #   hypothesis:
  #     theme: clean
  #     openSidebar: false        
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

