---
title: ""
date-modified: last-modified
---

## 데이터사이언스와 R

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund, 2023, [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.hadley.nz/)*,* 2nd edition, Boston: O’Reilly. 

-   Bonnell, Jerry, and Mitsunori Ogihara. 2023. [*Exploring Data Science with R and the Tidyverse*](https://ds4world.cs.miami.edu/). 1st edition. Chapman; Hall/CRC.

-   Irizarry, Rafael A. 2024. [*Introduction to Data Science: Data Wrangling and Visualization with R*](https://rafalab.dfci.harvard.edu/dsbook-part-1/). 2nd edition, Boca Raton: CRC Press.

-   한국알사용자회, [데이터 과학을 지탱하는 기본기](https://r2bit.com/book_analytics/), 웹북

-   김기환, 2023, [R 프로그래밍(개정판)](https://kilhwan.github.io/rprogramming/), 웹북

## 시각화

-   Wickham, Hadley. 2016. [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/). 2nd edition, Switzerland: Springer. (박진수 옮김, 2017. [R로 분석한 데이터를 멋진 그래픽으로 ggplot2](https://www.yes24.com/Product/Goods/57248968). 부천: 프리렉.)

-   Kabacoff, Robert, 2024, [*Modern Data Visualization with R*](https://rkabacoff.github.io/datavis/), Boca Raton: CRC Press.

## 쿼토 Quarto

-   [Quarto 웹사이트](https://quarto.org/)

-   한국알사용자회ㆍ이광춘, 2024, [챗GPT쿼토: 인공지능 시대 과학기술 저작 도구](https://r2bit.com/gpt-quarto/), 웹북

## 샤이니 Shiny

-   [Shiny 웹사이트](https://shiny.posit.co/)

-   Wickham, Hadley, 2021, [*Mastering Shiny: Build Interactive Apps, Reports, and Dashboards Power by R*](https://mastering-shiny.org/)*,* Sebastopol, CA: O’REILLY. (이영록 옮김, 2022, [R 사용자를 위한 Shiny 마스터 가이드](https://www.yes24.com/Product/Goods/116598818), 서울: 인사이트.)

-   Granjon, David, 2022, [*Outstanding User Interfaces with Shiny*](https://unleash-shiny.rinterface.com/), Boaca Raton: CRC Press.

-   Fay, Colin, Vincent Guyader, Sebastien Rochette, and Cervan Girard. 2022, [*Engineering Production-Grade Shiny Apps*](https://engineering-shiny.org/), Boca Raton: CRC Press.

## 
